const P=PropertiesService.getScriptProperties();
const SID=()=>P.getProperty("SHEET_ID");
const OWNER=()=>(P.getProperty("OWNER_EMAIL")||"h9302782@gmail.com").toLowerCase();
const CID=()=>P.getProperty("GOOGLE_CLIENT_ID");
const TZ=()=>Session.getScriptTimeZone()||"Asia/Kolkata";
function out(x){return ContentService.createTextOutput(JSON.stringify(x)).setMimeType(ContentService.MimeType.JSON)}
function doGet(e){try{const a=e.parameter.action||"";if(a==="health")return out({ok:true,service:"Forever",status:"UP"});if(a==="experience")return out(openExp(e.parameter.id));if(a==="getMedia")return out(getMedia(e.parameter.file_id));if(e.parameter.p)return out(openExp(e.parameter.p));return out({ok:true,service:"Forever"})}catch(x){return out({ok:false,error:String(x.message||x)})}}
function doPost(e){try{const b=JSON.parse(e.postData.contents||"{}");if(b.action==="login")return out(login(b.idToken));if(b.action==="createExperience")return out(create(b));if(b.action==="adminStats")return out(stats(b.idToken));throw Error("Unknown action")}catch(x){return out({ok:false,error:String(x.message||x)})}}
function verify(t){if(!t)throw Error("Google sign-in required.");const r=UrlFetchApp.fetch("https://oauth2.googleapis.com/tokeninfo?id_token="+encodeURIComponent(t),{muteHttpExceptions:true});if(r.getResponseCode()!=200)throw Error("Google sign-in token expired or invalid.");const g=JSON.parse(r.getContentText());if(g.aud!==CID())throw Error("OAuth client ID mismatch.");return {email:(g.email||"").toLowerCase(),name:g.name||g.email,sub:g.sub||""}}
function sh(n){const ss=SpreadsheetApp.openById(SID());let s=ss.getSheetByName(n);if(!s)s=ss.insertSheet(n);return s}
function rows(n){return sh(n).getDataRange().getValues()}
function now(){return new Date()}
function login(t){const g=verify(t),s=sh("Users"),r=rows("Users");let row=-1;for(let i=1;i<r.length;i++)if(String(r[i][2]).toLowerCase()===g.email){row=i+1;break}const n=now();if(row<0){s.appendRow(["usr_"+Utilities.getUuid().slice(0,8),g.sub,g.email,g.name,"",n,n,1,g.email===OWNER()?"owner":"user","active"])}else{s.getRange(row,7).setValue(n);s.getRange(row,8).setValue(Number(s.getRange(row,8).getValue()||0)+1)}sh("Events").appendRow(["evt_"+Utilities.getUuid().slice(0,8),g.email,"","login",n,"",g.email]);return {ok:true,user:{email:g.email,name:g.name,role:g.email===OWNER()?"owner":"user"}}}
function folder(){const it=DriveApp.getFoldersByName("Forever");return it.hasNext()?it.next():DriveApp.createFolder("Forever")}
function file_(f,folder,prefix){const b=Utilities.base64Decode(f.data);return folder.createFile(Utilities.newBlob(b,f.type||MimeType.BINARY,f.name||prefix)).getId()}
function create(b){const g=verify(b.idToken),id=Utilities.getUuid().replace(/-/g,"").slice(0,8).toUpperCase(),f=folder().createFolder(id),photo="",audio="";let pf="",af="";if(b.files&&b.files.photo)pf=file_(b.files.photo,f,"photo");if(b.files&&b.files.audio)af=file_(b.files.audio,f,"audio");const e=b.experience||{};f.createFile("experience.json",JSON.stringify({id,type:e.type,title:e.title,recipientName:e.recipientName,message:e.message||"",photoPath:pf,audioPath:af,price:Number(e.price||0),status:"active"}),MimeType.PLAIN_TEXT);sh("Experiences").appendRow([id,g.email,e.type,e.title,e.recipientName,e.message||"",f.getId(),pf,af,now(),e.expiresAt||"",0,Number(e.maxVisits||5),"active",Number(e.price||0)]);sh("Events").appendRow(["evt_"+Utilities.getUuid().slice(0,8),g.email,id,"experience_created",now(),"",e.title]);return {ok:true,id,url:"/p/"+id}}
function openExp(id){if(!id)throw Error("Missing experience id.");const r=rows("Experiences");let x=null;for(let i=1;i<r.length;i++)if(String(r[i][0])===String(id)){x=r[i];break}if(!x)throw Error("Experience not found.");if(String(x[13])!=="active")throw Error("Experience unavailable.");const expires=x[10];if(expires&&new Date(expires)<now())throw Error("EXPERIENCE_EXPIRED");const visits=Number(x[11]||0),max=Number(x[12]||0);if(max>0&&visits>=max)throw Error("EXPERIENCE_LIMIT_REACHED");sh("Experiences").getRange(r.findIndex(row=>String(row[0])===String(id))+1,13).setValue(visits+1);sh("Events").appendRow(["evt_"+Utilities.getUuid().slice(0,8),"",id,"experience_opened",now(),"",""]);return {ok:true,experience:{id:String(x[0]),type:String(x[2]),title:String(x[3]),recipientName:String(x[4]),message:String(x[5]),photoFileId:String(x[7]||""),audioFileId:String(x[8]||""),price:Number(x[14]||0),visitCount:visits+1,maxVisits:max}}}
function getMedia(fileId){if(!fileId)throw Error("Missing file_id");const f=DriveApp.getFileById(fileId),blob=f.getBlob();return {ok:true,dataUri:"data:"+blob.getContentType()+";base64,"+Utilities.base64Encode(blob.getBytes())}}
function stats(t){const g=verify(t);if(g.email!==OWNER())throw Error("Admin access denied.");const u=rows("Users"),e=rows("Experiences"),ev=rows("Events"),o=rows("Orders"),today=Utilities.formatDate(now(),TZ(),"yyyy-MM-dd");let nu=0,li=0,vi=0,views=0,rv=0,tr=0;u.slice(1).forEach(x=>{if(fmt(x[5])===today)nu++});ev.slice(1).forEach(x=>{if(fmt(x[4])===today){if(x[3]==="login")li++;if(x[3]==="experience_opened"){views++;vi++}}});const map={};o.slice(1).forEach(x=>{if(String(x[4]).toLowerCase()==="paid"){rv+=Number(x[3]||0);if(fmt(x[5])===today)tr+=Number(x[3]||0);const id=String(x[2]);map[id]=(map[id]||0)+1}});const top=e.slice(1).map(x=>({id:String(x[0]),title:String(x[3]),orders:map[String(x[0])]||0})).filter(x=>x.orders>0).sort((a,b)=>b.orders-a.orders).slice(0,10);return {ok:true,stats:{overall:{users:Math.max(0,u.length-1),visitors:ev.slice(1).filter(x=>x[3]==="experience_opened").length,experiences:Math.max(0,e.length-1),revenue:rv},today:{newUsers:nu,logins:li,visitors:vi,views,revenue:tr},topExperiences:top}}}
function fmt(x){return Utilities.formatDate(new Date(x),TZ(),"yyyy-MM-dd")}
function setup(){const ss=SpreadsheetApp.openById(SID()),m={Users:["user_id","google_id","email","name","photo_url","created_at","last_login","login_count","role","status"],Experiences:["experience_id","creator_id","type","title","recipient_name","message","drive_folder_id","experience_json_file_id","photo_file_id","audio_file_id","created_at","expires_at","visit_count","max_visits","status","price"],Events:["event_id","user_id","experience_id","event_type","timestamp","session_id","metadata"],Orders:["order_id","user_id","experience_id","amount","payment_status","created_at"],DailyStats:["date","new_users","total_logins","unique_visitors","experience_views","experiences_created","orders","revenue"]};Object.keys(m).forEach(n=>{const s=ss.getSheetByName(n)||ss.insertSheet(n);if(s.getLastRow()===0)s.appendRow(m[n])})}
